server:
  port: 8087

rosco:
  configDir: /opt/rosco/config/packer
  jobs:
    local:
      timeoutMinutes: 30

redis:
  connection: ${services.redis.baseUrl:redis://localhost:6379}

spectator:
  applicationName: ${spring.application.name}
  webEndpoint:
    enabled: false

packer:
  # Set this if running Packer >= 1.4.0 for timestamp prepended output
  timestamp: false
  # Add additional parameters that will always be passed to "packer build" here
  # additionalParameters:
    # - on-error=abort
    # - -var "bakedBy=Rosco"

# If a repository is set here, it will be added by packer as repository when baking images for GCE and AWS.
# It is safe to leave this out (or blank) if you do not need to configure your own repository.
# You can specify an apt repository (used when baking debian based images) and/or a yum repository (used when baking an
# rpm based imaged) and/or a chocolatey repository (used when baking a nuget based image).
# You may specify a space separated list repositories per repository type.
# The following commented-out lines are an example of what a valid entry looks like.
# debianRepository: http://dl.bintray.com/spinnaker/ospackages trusty main;http://other.repo.com/repo/packages trusty main
# yumRepository: https://jfrog.bintray.com/yum/repos/some-package
# chocolateyRepository: https://chocolatey.org/api/v2/
# This general repository can be override at BaseImage level using customRepository entry


defaultCloudProviderType: aws

# When the bakery is configured to use a templateFile in this list,
# /usr/bin/packer will be run as root using 'sudo'.
# By default, spinnaker does not have sudo permissions so these scripts will
# fail.
# In order to give sudo permissions, create and add the following line (without
# leading '#') to /etc/sudoers.d/spinnaker
# spinnaker ALL=(ALL) NOPASSWD: /usr/bin/packer
#
# WARNING: Giving sudo access for spinnaker to execute packer may create an
# opportunity for malicious actors to take control of your machine and data it
# has access to.

templatesNeedingRoot: aws-chroot.json

swagger:
  enabled: true
  title: Spinnaker Rosco API
  description:
  contact:
  patterns:
    - /api/v1.*
    - /api/v2.*
    - /bakeOptions.*
    - /status.*
springdoc:
  writer-with-default-pretty-printer: true
  swagger-ui:
    display-request-duration: true
    disable-swagger-default-url: true
    url: /v3/api-docs.yaml
  api-docs:
    version: openapi_3_0
